name: Presentation Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: echo "Simulating unit tests... PASSED"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build Artifact
        run: echo "Building application container..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Deployment Script
        run: bash deploy.sh
