- name: Deploy
  uses: appleboy/ssh-action@v1.2.2
  with:
    host: ${{ secrets.PA_HOSTNAME }}
    username: ${{ secrets.PA_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    debug: true
    script: |
      set -xe

      cd /home/blu5ir/Task_flow

      git fetch origin
      git reset --hard origin/main
      git clean -fd

      source /home/blu5ir/Task_flow/venv/bin/activate

      pip install -r requirements.txt

      touch /var/www/blu5ir_pythonanywhere_com_wsgi.py

      echo "Deployment successful!"
