name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PA_HOSTNAME }}
          username: ${{ secrets.PA_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /home/blu5ir/deploy.sh
